name: Deploy and Release Plugin to WP.org

on:
    push:
        tags:
            - "*"
jobs:
    releaseToWPOrg:
        name: Release to WordPress.org
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install SVN ( Subversion )
              run: |
                sudo apt-get update
                sudo apt-get install -y subversion
            - name: WordPress Plugin Deploy
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              with:
                generate-zip: true
              env:
                SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                SLUG: dokan-invoice
            - name: Create GitHub release
              uses: softprops/action-gh-release@v2
              with:
                files: ${{steps.deploy.outputs.zip-path}}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
